### ISSUE TITLE
fix: empty `org.opencontainers.image.version` label

### ISSUE THREAD

**Issue by xynydev** [ublue-os/bluefin#411] opened 2023-08-15 17:42 UTC
This is a small issue related to the container's labels.
Some code, such as startingpoint, parses the OS version from `org.opencontainers.image.version` to use as a tag, but in bluefin images the label seems to be empty, while the correct content _is_ in the `version` label.

 ```sh
❯ skopeo inspect docker://ghcr.io/ublue-os/bluefin:latest | jq -r '.Labels'
{
  "io.artifacthub.package.logo-url": "https://avatars.githubusercontent.com/u/120078124?s=200&v=4",
  "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/ublue-os/bluefin/bluefin/README.md",
  "io.buildah.version": "1.23.1",
  "org.opencontainers.image.created": "2023-08-15T10:02:40.119Z",
  "org.opencontainers.image.description": "An interpretation of the Ubuntu spirit built on Fedora technology",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.revision": "f7652c29d50328c3754bdee2123c01531e9ca6f5",
  "org.opencontainers.image.source": "https://github.com/ublue-os/bluefin",
  "org.opencontainers.image.title": "bluefin",
  "org.opencontainers.image.url": "https://github.com/ublue-os/bluefin",
  "org.opencontainers.image.version": "",
  "ostree.bootable": "true",
  "ostree.commit": "e333bf9858fa928170a97cb349117c812039d5b65920a35e56b2b36c2e7df522",
  "ostree.final-diffid": "sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1",
  "ostree.linux": "6.4.10-200.fc38.x86_64",
  "quay.expires-after": "4w",
  "rpmostree.inputhash": "12795892b5e7a226b9576c14f6c1974a8f26f8035054efd864b8eb31900b871a",
  "version": "38.20230815.0"
}
```

Issue found here https://github.com/ublue-os/startingpoint/pull/140

**Comment by p5** [comment] 2023-10-01 15:35
Think we can now close this.  Not sure when it changed, but now the `image.version` label is present:

```
skopeo inspect docker://ghcr.io/ublue-os/bluefin:latest | jq -r '.Labels'
{
  "io.artifacthub.package.logo-url": "https://avatars.githubusercontent.com/u/120078124?s=200&v=4",
  "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/ublue-os/bluefin/bluefin/README.md",
  "io.buildah.version": "1.23.1",
  "org.opencontainers.image.created": "2023-10-01T14:05:08.012Z",
  "org.opencontainers.image.description": "An interpretation of the Ubuntu spirit built on Fedora technology",
  "org.opencontainers.image.licenses": "Apache-2.0",
  "org.opencontainers.image.revision": "5277f5af7d77e50199fa7a49caa98b7f63638132",
  "org.opencontainers.image.source": "https://github.com/ublue-os/bluefin",
  "org.opencontainers.image.title": "bluefin",
  "org.opencontainers.image.url": "https://github.com/ublue-os/bluefin",
  "org.opencontainers.image.version": "38.20231001.0",
  "ostree.bootable": "true",
  "ostree.commit": "39e85b0cbd078cd373ad39974979ab0d76feeaf66f2400e0f4356cd5ad96666a",
  "ostree.final-diffid": "sha256:12787d84fa137cd5649a9005efe98ec9d05ea46245fdc50aecb7dd007f2035b1",
  "ostree.linux": "6.5.5-200.fc38.x86_64",
  "quay.expires-after": "4w",
  "rpmostree.inputhash": "7c6a329cf6fb434bf925149c7930642e30959dbb9cc503e9b350cbda94877347",
  "version": "38.20231001.0"
}
```

If the issue is still there, please reopen

**Closed by p5** 2023-10-01 15:35 UTC
