### ISSUE TITLE
Clicking from flatpak apps doesn't open the browser

### ISSUE THREAD

**Issue by castrojo** [ublue-os/bluefin#575] opened 2023-10-09 19:18 UTC
Had someone report this to me earlier today and I've seen this happen on 2 machines, logging out and back in seems to mitigate it, I think there's some flatpak/xdg service breaking somewhere.

**Comment by aadilayub** [comment] 2023-10-10 13:01
Happened to me. Logging back in and out fixed it. I have a feeling it might be triggered by Will post here if it happens again!

**Comment by castrojo** [comment] 2023-10-10 15:56
Looks like it comes back after a reboot, so current workaround is to log out after a clean boot and log back in.

Oh boy, this seems to be a thing:

- https://github.com/flatpak/flatpak/issues/1508

**Comment by bronson** [comment] 2023-10-10 22:38
It does appear flatpak-related. Opening a URL with `xdg-open` from the terminal works fine.

The logs show (among a whole bunch of other output):

```txt
C28: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B14915: <- :1.13 return error org.freedesktop.DBus.Error.UnknownMethod from C28
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.OpenURI? on object at path /org/freedesktop/portal/desktop
B-1: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameOwnerChanged at /org/freedesktop/DBus
C66: -> :1.73 call org.freedesktop.IBus.InputContext.Reset at /org/freedesktop/IBus/InputContext_37
C1: -> org.freedesktop.DBus call org.freedesktop.DBus.Hello at /org/freedesktop/DBus
```

So that's similar to what others were seeing in https://github.com/flatpak/flatpak/issues/1508

**Comment by castrojo** [comment] 2023-10-10 22:43
So far this appears to be bluefin specific that has been occuring in the past few days. `xdg-desktop-portal-gtk` hasn't changed recently. 

I'm trying to think of what we changes we have over stock that could be causing this but coming up empty so far.

**Comment by bronson** [comment] 2023-10-10 22:56
There's a checklist in https://github.com/flatpak/flatpak/issues/1508#issuecomment-1702714679

Going through it...

* Opening links in non-Flatpak needs to work. :heavy_check_mark: `gio open https://example.com` works
* `systemctl --user show-environment` needs to show at least the DISPLAY, XDG_CURRENT_DESKTOP, WAYLAND_DISPLAY, DISPLAY, XAUTHORITY ... :heavy_check_mark: Yep, all look good.
* You need xdg-desktop-portal installed :heavy_check_mark: Yep, /usr/libexec/xdg-desktop-portal
* You need a Flatpak app that can open links. :heavy_check_mark: Discord seems a reproducible case.
* You need at least one portal backend :heavy_check_mark: I guess xdg-desktop-portal-gnome
* You need a portals.conf :heavy_check_mark: Yes, at /usr/share/xdg-desktop-portal/gnome-portals.conf

Those seem satisfied.

**Comment by bronson** [comment] 2023-10-10 23:17
Running this command seems to fix the issue:

```txt
/usr/libexec/xdg-desktop-portal --verbose --replace
```

(if that alone doesn't fix it, then also running `/usr/libexec/xdg-desktop-portal-gtk --verbose --replace` should do it)

But that makes it kinda hard to capture failed log messages.

**Comment by zelikos** [comment] 2023-10-11 16:42
> So far this appears to be bluefin specific that has been occuring in the past few days. `xdg-desktop-portal-gtk` hasn't changed recently.
> 
> I'm trying to think of what we changes we have over stock that could be causing this but coming up empty so far.

This isn't bluefin-specific. I run into it on my own image, too

**Comment by castrojo** [comment] 2023-10-11 23:08
Running `/usr/libexec/xdg-desktop-portal --verbose --replace` launches without error but I am unable to open links still. Logging out and in also doesn't seem to fix it any more.

**Comment by bronson** [comment] 2023-10-19 17:08
@castrojo can you see if `/usr/libexec/xdg-desktop-portal-gnome --verbose --replace` or `/usr/libexec/xdg-desktop-portal-gtk --verbose --replace` affect it?  (just using the -gnome and -gtk variants)

**Comment by castrojo** [comment] 2023-10-29 22:37
(Been to busy to chase this down until now)

Using the 2nd one just fixed my discord, but there's nothing in the terminal output from either command that seems to be related to this. :-/

**Comment by liaralabs** [comment] 2023-11-07 07:27
Disclaimer: I'm running Bazzite but suffer the same issue and your discussion thus far has been relevant to me.

I enabled verbose logging in the xdg-desktop-portal service to get a better idea of what was going on during first login.

What sticks out to me is this:

```
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.MemoryMonitor
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.PowerProfileMonitor
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.NetworkMonitor
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.ProxyResolver
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.Trash
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.GameMode
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: providing portal org.freedesktop.portal.Realtime
Nov 06 23:11:09 xxx xdg-desktop-por[2433]: No skeleton to export
Nov 06 23:11:09 xxx xdg-desktop-portal[2433]: XDP: org.freedesktop.portal.Desktop acquired
Nov 06 23:11:09 xxx systemd[2324]: Started xdg-desktop-portal.service - Portal service.
Nov 06 23:11:12 xxx xdg-desktop-portal[2433]: XDP: No 'realtime' permissions found: No entry for realtime
Nov 06 23:11:12 xxx xdg-desktop-portal[2433]: XDP: No 'realtime' permissions found: No entry for realtime
Nov 06 23:11:12 xxx xdg-desktop-portal[2433]: XDP: No 'realtime' permissions found: No entry for realtime
Nov 06 23:11:12 xxx xdg-desktop-portal[2433]: XDP: No 'realtime' permissions found: No entry for realtime
Nov 06 23:11:13 xxx xdg-desktop-portal[2433]: XDP: No 'realtime' permissions found: No entry for realtime
Nov 06 23:11:13 xxx xdg-desktop-portal[2433]: XDP: No 'realtime' permissions found: No entry for realtime
```

The startup of the portal hangs at this point. I assume this is why it doesn't open links -- the process is stalled. If I come along and restart xdg-desktop-portal at this point, it chugs for a second, times out and does a complete restart. When it restarts it doesn't have any issues loading the realtime entries.

I'll keep digging about the realtime portal when I have some time, but wanted to pass this along in case it helps others debug here.

**Comment by bronson** [comment] 2023-11-07 20:33
> I enabled verbose logging in the xdg-desktop-portal service

Nice. How did you do this? I'm not seeing it in /etc or systemctl.

**Comment by liaralabs** [comment] 2023-11-07 20:38
xdg-desktop-portal is a user service, so it doesn't live at the system level. Easy way:

```
systemctl --user edit xdg-desktop-portal
```

Between the comment lines indicating where to edit:

```
[Service]
ExecStart=
ExecStart=/usr/libexec/xdg-desktop-portal --verbose
```

Give things a daemon-reload and restart the service (check it's working properly before you restart)

```
systemctl --user daemon-reload
systemctl --user restart xdg-desktop-portal
```

Verify the status
```
systemctl --user status xdg-desktop-porta
```

View logs:
```
journalctl --user -u xdg-desktop-portal
```

Then reboot to trigger the fail scenario and investigate your fresh logs

**Comment by liaralabs** [comment] 2023-11-08 02:27
One of my top suspects at the moment is that this is a potential race condition since everything is fixed with a restart after some arbitrary amount of time has passed.

With that in mind, I tried debugging further by adding a short sleep before the ExecStart (`ExecStartPre=/usr/bin/sleep 5`). Interestingly, 1 second isn't enough, but 5 seems to break the pattern just enough to let other issues surface.

While the issue isn't fixed by any stretch of the imagination, what I'm now seeing is the behavior which is currently being triggered by the manual restart of the portal to fix the bug.

Upon logging in, xdg-desktop-portal gets stuck in an Activating state. The activation eventually times out with the error:
```
Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached
```

The service dies, then restarts and when it restarts it's a fully functioning portal. This doesn't require any intervention on my behalf, but anything relying on the portal to start (i.e. Syncthingy, Firefox) will hang until the portal properly starts.

Not really a fix, more of a sidegrade in terms of functionality. Ultimately, flatpaks aren't very usable if the portal isn't online in any capacity at all (i.e. Firefox will take a long time to start up)

**Comment by ethanjli** [comment] 2023-11-08 07:31
After I rebased from ghcr.io/ublue-os/kinoite-nokmods:39 to the `-dx:39` version of my new (as of this morning) personalized fork of bluefin, which I modified to be based on Kinoite instead of Silverblue, I started noticing the same `No such interface ?org.freedesktop.portal.OpenURI?` errors, e.g. when trying to open links on Slack. However, on my system I have yet not been able to identify a Flatpak app which can open links on my Bluefin fork (Discord and Spotify both are unable to open links for me, though both have been mentioned as working cases by other people in the context of this issue), though I can confirm that the other elements of [the checklist](https://github.com/ublue-os/bluefin/issues/575#issuecomment-1756402029) are satisfied with the KDE equivalents for xdg-related stuff.

After I rebased back to ghcr.io/ublue-os/kinoite-main:39, I confirmed that I was able to open links from the Slack, Discord, and Spotify Flatpak apps. And after I rebased to the non-dx `:39` version of my fork of bluefin, I confirmed that I could not open links anymore from those three Flatpak apps; and that logging out and logging back restored the ability to open links from those apps; and that rebooting removed the ability to open links from those three apps.

Interestingly, rebasing to my bluefin fork also causes two installed Flatpak apps (Syncthingy and Crow) and two rpm-ostree programs (kdeconnectd and xwaylandvideobridge) to crash and coredump - these crashes don't occur on ghcr.io/ublue-os/kinoite-main:39. It's very possible that these crashes are unrelated problems, but just in case they might be relevant, I've attached the system logs obtained with `journalctl -p 3 -xb`:
[bluefin-fork.log](https://github.com/ublue-os/bluefin/files/13293240/bluefin-fork.log)
[kinoite.log](https://github.com/ublue-os/bluefin/files/13293238/kinoite.log)

My next step for troubleshooting is to see if I can isolate any causal difference(s) for this symptom between ghcr.io/ublue-os/kinoite-main:39 and my Bluefin fork, by removing all changes made by the Containerfile over Kinoite and confirming that the result behaves identically to Kinoite (i.e. able to open links from Slack), and then progressively bisecting the changes made by my Bluefin fork's Containerfile. I'm not yet confident that the cause of my problem is the same as the cause of the problem in Bluefin - hopefully this next troubleshooting step will provide some clarity on that (and teach me more about what the Bluefin Containerfile is doing 😄  ).

**Comment by zelikos** [comment] 2023-11-08 17:27
After commenting out the `Requires=xdg-desktop-autostart.target` line in the equivalent service file in my startingpoint image and rebooting, I can confirm that I'm also able to open links again just fine. The service file also *seems* to still activate just fine without that line, but more testing should be done there to be sure.

**Comment by liaralabs** [comment] 2023-11-09 01:45
It's a good find (for any bazzite users here, the user service in our distro is called bazzite-user-setup.service).

The proposed fix still sees `Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached` before it terminates and restarts itself. Upon this restart, everything works normally.

This basically appears to be an equivalent fix to the sleep 5 pre-exec command I had noted earlier.

With this proposed fix, firefox still hangs for some 20-30 seconds before launching on a fresh boot (SyncThingy as well). 

Now, if bluefin users on Gnome don't have any such issues with this proposed fix, we may be entering the realm of a KDE-specific (or maybe something else in bazzite) bug.

**Comment by KyleGospo** [comment] 2023-11-09 01:47
Very nice find, I'll fix that up now in a few PRs.

**Comment by liaralabs** [comment] 2023-11-09 01:58
I managed to resolve this completely for KDE with some additional tinkering!

In the service file for plasma-xdg-desktop-portal-kde there's an After=xdg-desktop-portal.service

I reviewed the upstream files here and no such after exists.

I commented that out so the service file for the plasma portal is now:

```
[Unit]
Description=Xdg Desktop Portal For KDE
PartOf=graphical-session.target
After=plasma-core.target
#After=xdg-desktop-portal.service

[Service]
ExecStart=/usr/libexec/xdg-desktop-portal-kde
BusName=org.freedesktop.impl.portal.desktop.kde
Slice=session.slice
# Auto restart is off as we are DBus activated
Restart=no
```

Everything is good now with KDE!

**Comment by ethanjli** [comment] 2023-11-09 02:40
Here are the conditions I found which appeared to be sufficient to trigger the `No such interface ?org.freedesktop.portal.OpenURI?` error:
- In Bluefin: `ublue-user-setup.service` has a dependency on `app-com.github.zocker_160.SyncThingy@autostart.service`, either directly (via `Requires=app-com.github.zocker_160.SyncThingy@autostart.service`) or indirectly (via `Requires=xdg-desktop-autostart.target`), and SyncThingy is installed.
  - When both conditions are active together, they cause the error; when only one of those two conditions is active, it is not sufficient to cause the error. 
  - When `ublue-user-setup.service` has a dependency on any or all of the other apps included in `xdg-desktop-autostart.target`, that is not sufficient to cause the error.
  - With the conditions resulting in the error, I am able to reproduce the `xdg-desktop-portal` log messages in https://github.com/ublue-os/bluefin/issues/575#issuecomment-1797948742
- In my Kinoite-based Bluefin fork (which runs KDE and also has SyncThingy installed): `ublue-user-setup.service` has a dependency on `app-org.kde.kdeconnect.daemon@autostart.service`, either directly or indirectly.
  - When `ublue-user-setup.service` has a dependency on any or all of the other apps included in `xdg-desktop-autostart.target`, **such as `app-com.github.zocker_160.SyncThingy`**, that is not sufficient to cause the error.

I don't have an explanation for why SyncThingy appears to be relevant in GNOME but irrelevant in KDE and why KDE Connect is relevant in KDE. Maybe they have some interaction with `xdg-desktop-portal` which results in the behavior liaralabs described?

As for the proposed fixes:

I haven't had a chance to test out the KDE-specific fix proposed in https://github.com/ublue-os/bluefin/issues/575#issuecomment-1803044766 for my KDE-based Bluefin fork, but after I removed all Requires dependencies of `ublue-user-setup.service` and restarted, SyncThingy had launched immediately with no delay and was able to open a link in my browser immediately when I clicked it. In my Kinoite-based Bluefin fork, `xdg-desktop-portal,service` is naturally a dependency of `graphical.target` and is not mentioned by `plasma-xdg-desktop-portal-kde.service` - so maybe there's also a Bazzite-specific issue on top of whatever is going on with `xdg-desktop-autostart`'s dependency relationships?

```
> systemctl list-dependencies --user xdg-desktop-portal.service --all --reverse
xdg-desktop-portal.service
● └─graphical-session.target
●   └─plasma-workspace.target
●     └─plasma-workspace-wayland.target

> cat /usr/lib/systemd/user/plasma-xdg-desktop-portal-kde.service
[Unit]
Description=Xdg Desktop Portal For KDE
PartOf=graphical-session.target
After=plasma-core.target

[Service]
ExecStart=/usr/libexec/xdg-desktop-portal-kde
BusName=org.freedesktop.impl.portal.desktop.kde
Slice=session.slice
# Auto restart is off as we are DBus activated
Restart=no
```

Regarding the fix for Bluefin/GNOME, if we need `ublue-user-setup.service` to express a `Requires`/`Wants` dependency on an application started as part of `[xdg-desktop-autostart.target](http://xdg-desktop-autostart.target/)`, such as `app-bluefin\x2dfirstboot@autostart.service` which corresponds to the `~/.config/autostart/bluefin-firstboot.desktop` file which runs `/usr/bin/yafti /etc/yafti.yml`, then I would suggest expressing that dependency directly (e.g. `Requires=app-bluefin\x2dfirstboot@autostart.service`), rather than indirectly via `[Requires=xdg-desktop-autostart.target](http://requires=xdg-desktop-autostart.target/)`.

**Comment by liaralabs** [comment] 2023-11-09 03:50
Yeah, sorry about that, may have led you slightly astray. `Failed to create settings proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.kde: Timeout was reached` was a race condition in the bazzite kde base and fixed by the commit referenced right above your reply.

**Closed** 2023-12-17 15:18 UTC
Labels: help wanted

**Comment by tduck973564** [comment] 2024-09-25 04:12
Strangely enough I'm seeing this exact issue right now on my own image derived from Kinoite. The service instantly dies with `The Wayland connection broke. Did the Wayland compositor die?`, and `Main process exited, code=exited, status=255/EXCEPTION`.
